language: php

php:
  - 5.5
  - 5.6

before_install:
  - travis_retry composer self-update

install:
  - travis_retry composer install --prefer-source --no-interaction

before_script:
  - cp .env.travis .env

script:
  - vendor/bin/phpunit --verbose --coverage-text
